version: '3'
services:
    redis:
      image: redis
      networks:
        - back-tier
    
    db:
      image: postgres
      environment:
        POSTGRES_USER: "postgres"
        POSTGRES_PASSWORD: "postgres"
      volumes:
        - "db-data:/var/lib/postgresql/data"
      networks:
        - back-tier
    
    vote:
      image: voting-app
      ports:
        - 5000:80
      networks:
        - front-tier
        - back-tier
    
    result:
      image: result-app
      ports:
        - 5001:80
      networks:
        - front-tier
        - back-tier
    
    worker:
      image: worker
      networks:
        - back-tier

volumes:
    db-data:

networks:
    front-tier:
    back-tier:
